#!/bin/busybox sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev

#echo -e "Auto memory test\n" >> /dev/console
#/bin/busybox sh /bench/memtest.sh /bench 1 < /dev/console > /dev/console 2>&1

#echo -e "Auto DMA test\n" >> /dev/console
#/bin/busybox sh /bench/dmatest.sh < /dev/console > /dev/console 2>&1

#echo -e "Auto Litmus test\n" >> /dev/console
#/bin/busybox sh /bench/litmus.sh /bench 4 7 < /dev/console > /dev/console 2>&1

#echo -e "Auto TAR benches multi-process\n" >> /dev/console
#/bin/busybox sh /bench/bench-auto-mp.sh 4 7 < /dev/console > /dev/console 2>&1

/bin/busybox sh < /dev/console > /dev/console 2>&1
